# Generated by Django 3.1.1 on 2020-09-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='back_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front_description',
            field=models.TextField(),
        ),
    ]
