# Generated by Django 3.1.1 on 2020-09-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200912_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashCard',
        ),
    ]
