# Generated by Django 3.1.1 on 2020-09-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('blog', '0007_delete_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_content', models.CharField(max_length=256)),
                ('front_image_link', models.TextField(blank=True, null=True)),
                ('back_content', models.CharField(max_length=256)),
                ('front_description', models.TextField(blank=True, null=True)),
                ('back_description', models.TextField(blank=True, null=True)),
                ('back_image_link', models.TextField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_flashcard', to='blog.blog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_flashcard', to='base.member')),
            ],
        ),
    ]
