# Generated by Django 3.1.1 on 2020-09-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('blog', '0008_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_blog', to='base.Member'),
        ),
    ]
