# Generated by Django 3.1.1 on 2020-09-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogcluster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCluster',
        ),
    ]
