# Generated by Django 3.1.1 on 2020-09-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200920_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcluster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
