# Generated by Django 3.1.1 on 2020-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogcluster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcluster',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
