# Generated by Django 3.1.1 on 2020-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogcluster_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcluster',
            name='totalViews',
            field=models.IntegerField(default=0),
        ),
    ]
