# Generated by Django 3.1.1 on 2020-09-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('blog', '0021_blog_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_set', to='blog.blog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_set', to='base.member')),
            ],
        ),
    ]
