# Generated by Django 3.1.1 on 2020-09-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_cardset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
