# Generated by Django 3.1.1 on 2020-09-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_cardset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='member',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='card_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='blog.cardset'),
            preserve_default=False,
        ),
    ]
