# Generated by Django 3.1.1 on 2020-09-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_member_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Kien', max_length=256),
            preserve_default=False,
        ),
    ]
